# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga_horaria', models.IntegerField()),
                ('nome', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=20)),
                ('professor', models.CharField(max_length=20)),
            ],
        ),
    ]
