# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 02:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemAluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=100, verbose_name='Assunto')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Aluno')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Professor')),
            ],
        ),
        migrations.RemoveField(
            model_name='turma',
            name='identificacao_turma',
        ),
        migrations.AddField(
            model_name='turma',
            name='turma',
            field=models.CharField(db_column='Identificacao_Turma', default='null', max_length=5),
            preserve_default=False,
        ),
    ]
