# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 23:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171023_2146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
