# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171127_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='id_professor',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='core.Professor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questao',
            name='data',
            field=models.DateTimeField(db_column='Data'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='data_de_envio',
            field=models.DateTimeField(db_column='Data_de_Envio'),
        ),
    ]
