# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_delete_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga_horaria', models.IntegerField(verbose_name='Carga Horária')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome')),
                ('tipo', models.CharField(max_length=20, verbose_name='Tipo')),
                ('professor', models.CharField(max_length=20, verbose_name='Professor')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
        ),
    ]
