# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_questao_id_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='turma',
            field=models.ForeignKey(db_column='ID_Turma', default='1', on_delete=django.db.models.deletion.CASCADE, to='core.Turma'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questao',
            name='data_limite_entrega',
            field=models.DateTimeField(db_column='Data_Limite_Entrega', max_length=10),
        ),
        migrations.RemoveField(
            model_name='questao',
            name='id_turma',
        ),
        migrations.AlterUniqueTogether(
            name='questao',
            unique_together=set([('turma', 'numero')]),
        ),
    ]
