# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=50, verbose_name='Assunto')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('carga_horaria', models.IntegerField(verbose_name='Carga Horária')),
                ('teoria', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Teoria')),
                ('pratica', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Prática')),
                ('ementa', models.TextField(verbose_name='Ementa')),
                ('competencias', models.TextField(verbose_name='Competencias')),
                ('habilidades', models.TextField(verbose_name='Habilidades')),
                ('conteudo', models.TextField(verbose_name='Conteudo')),
                ('bibliografia_basica', models.TextField(verbose_name='Bibliografia Básica')),
                ('bibliografia_complementar', models.TextField(verbose_name='Bibliografia Complementar')),
            ],
        ),
    ]
