# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20171127_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Turma'),
        ),
    ]
