# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20171127_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='turma',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='core.Turma'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='questao',
            unique_together=set([('turma', 'numero')]),
        ),
    ]
