# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20171127_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resposta',
            name='id_professor',
        ),
        migrations.AddField(
            model_name='questao',
            name='id_turma',
            field=models.ForeignKey(db_column='ID_Turma', default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Turma'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resposta',
            name='data_avaliacao',
            field=models.ForeignKey(db_column='Data_Avaliacao', max_length=10, on_delete=django.db.models.deletion.CASCADE, to='core.Questao'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='data_de_envio',
            field=models.DateTimeField(db_column='Data_de_Envio', max_length=10),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='id_questao',
            field=models.ForeignKey(db_column='ID_Questao', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Questao'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='nota',
            field=models.DecimalField(db_column='Nota', decimal_places=2, max_digits=4, null=True),
        ),
        migrations.RemoveField(
            model_name='questao',
            name='turma',
        ),
        migrations.AlterUniqueTogether(
            name='questao',
            unique_together=set([('id_professor', 'id_turma', 'numero')]),
        ),
    ]
