# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_resposta_data_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='data_avaliacao',
            field=models.ForeignKey(db_column='Data_Avaliacao', default='1', max_length=10, on_delete=django.db.models.deletion.CASCADE, to='core.Questao'),
            preserve_default=False,
        ),
    ]
