# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_resposta_data_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='id_turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Turma'),
        ),
    ]
