# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20171127_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='data',
            field=models.DateTimeField(db_column='Data', max_length=10),
        ),
        migrations.AlterField(
            model_name='questao',
            name='id_turma',
            field=models.ForeignKey(db_column='ID_Turma', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Turma'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='data_avaliacao',
            field=models.DateTimeField(db_column='Data_Avaliacao', max_length=10),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='id_questao',
            field=models.ForeignKey(db_column='ID_Questao', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Questao'),
        ),
        migrations.RemoveField(
            model_name='questao',
            name='id_professor',
        ),
        migrations.AlterUniqueTogether(
            name='questao',
            unique_together=set([('id_turma', 'numero')]),
        ),
    ]
