# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_questao_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='data_limite_entrega',
            field=models.DateField(db_column='Data_Limite_Entrega', max_length=10),
        ),
    ]
