# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_questao_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='avaliacao',
            field=models.TextField(db_column='Avaliacao', null=True),
        ),
    ]
