# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20171127_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(default='A', max_length=1, verbose_name='Perfil'),
        ),
    ]
